#!/system/bin/sh
#added by link2sd
LOG=/data/link2sd-11link2sd.log
set +e
echo "$(date) mounting..." > $LOG
sleep 2
mount -t ext2 -o rw /dev/block/vold/179:2 /data/sdext2 1>>$LOG 2>>$LOG

mount -t ext2 -o rw /dev/block/mmcblk0p2 /data/sdext2 1>>$LOG 2>>$LOG

mount >> $LOG
echo "$(date) mount finished" >> $LOG
chmod 773 /data/dalvik-cache
